### ISSUE TITLE
发现你fork了我的 IIGuideViewController 项目

### ISSUE THREAD

**Issue by ghost** [HotWordland/WebNewsJSBridgeOC#4]
哈哈搜索发现好多人fork了我的 IIGuideViewController 项目，因为这个项目之前是随便写的，现在更新了一个新的：https://github.com/whatsbug/IGuide
欢迎来测试bug哈

**Comment by HotWordland** [comment]
好的~👌

**Comment by ghost** [comment]
哈哈因为在fork的项目里面提不了issue，所以就在这个项目里告诉你一下，希望你不介意
